version: '3.4'

services:
  csproject.product.api:
    restart: always
    image: ${DOCKER_REGISTRY-}csprojectproductapi
    build:
      context: .
      dockerfile: CSProject.Product.Api/Dockerfile
    environment:
      ConsulServer: "csproject.product.api"
      
  csproject.auth:
    image: ${DOCKER_REGISTRY-}csprojectauth
    build:
      context: .
      dockerfile: CSProject.Auth/Dockerfile
      
  csproject.gateway.api:
    image: ${DOCKER_REGISTRY-}csprojectgatewayapi
    build:
      context: .
      dockerfile: CSProject.Gateway.Api/Dockerfile

  consul-server:
    image: consul:1.9.3
   
  ms-sql-server:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu