version: '3.4'

services:
  csproject.gateway.api:
    image: ${DOCKER_REGISTRY-}csprojectgatewayapi
    build:
      context: .
      dockerfile: CSProject.Gateway.Api/Dockerfile

  csproject.seeddata:
    restart: always
    image: ${DOCKER_REGISTRY-}seeddata
    build:
      context: .
      dockerfile: CSProject.SeedData/Dockerfile

  csproject.auth:
    image: ${DOCKER_REGISTRY-}csprojectauth
    build:
      context: .
      dockerfile: CSProject.Auth/Dockerfile

  csproject.product.api:
    restart: always
    image: ${DOCKER_REGISTRY-}csprojectproductapi
    build:
      context: .
      dockerfile: CSProject.Product.Api/Dockerfile
    environment:
      ConsulServer: "csproject.product.api"

  csproject.basket.api:
    restart: always
    image: ${DOCKER_REGISTRY-}csprojectbasketapi
    build:
      context: .
      dockerfile: CSProject.Basket.Api/Dockerfile
    environment:
      ConsulServer: "csproject.basket.api"

  consul-server:
    image: consul:1.9.3
   
  ms-sql-server:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu